#
# © Rolling Array https://rollingarray.co.in/
#
# @summary Deploy C2 Help & Support Prod api on prod branch push 
# @author code@rollingarray.co.in
#
# Created at     : 2021-05-26 10:42:18 
# Last modified  : 2021-11-04 09:22:42
#

name: Deploy C2 Help & Support API DEV api on DEV branch push

on: 
  push:
    branches: 
      - prod
      
jobs:
  web-deploy:

    name: Deploy C2 Help & Support Api Prod
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://c2.doc.api.rollingarray.co.in/

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Install Dependencies
      run: composer update --ignore-platform-reqs

    - name: Create .env file
      run: |
        cat << EOF > .env

        # database
        DB_USERNAME = ${{ secrets.DB_USERNAME}}
        DB_PASSWORD = ${{ secrets.DB_PASSWORD}}
        DATABASE = ${{ secrets.DATABASE}}
        DB_HOST = ${{ secrets.DB_HOST}}
        DB_PORT = ${{ secrets.DB_PORT}}
        
        EOF
      
    - name: Directory Permissions
      run: chmod -R 777 vendor

    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER}}
        username: ${{ secrets.FTP_USERNAME}}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.FTP_DEPLOYMENT_PATH }}
        dangerous-clean-slate: true